# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# CHANGED: Copy the .csproj file from current directory (no prefix needed)
COPY ["TaskTracker.API.csproj", "."]
RUN dotnet restore "./TaskTracker.API.csproj"
COPY . .
# CHANGED: We're already in the project directory, no need to change
RUN dotnet build "./TaskTracker.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# ORIGINAL:
#COPY ["TaskTracker.API/TaskTracker.API.csproj", "TaskTracker.API/"]
#RUN dotnet restore "./TaskTracker.API/TaskTracker.API.csproj"
#COPY . .
#WORKDIR "/src/TaskTracker.API"
#RUN dotnet build "./TaskTracker.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TaskTracker.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskTracker.API.dll"]